### ISSUE TITLE
安装包问题

### ISSUE THREAD

**Issue by John122-art** [daetz-coder/VectorNet_Code_Replication#1]
环境里面的安装包你是根据yet-another-vectornet里的安装包安装的吗？

**Comment by daetz-coder** [comment]
不是根据yet-another-vectornet的requirements.txt进行安装的，大部分都是常见的依赖，直接pip就行，有几点需要注意的是：

1. 安装argoverse-api时可能会出现numpy版本错误，修改`setup.py`中的版本即可
2. 安装PyG及其Additional Libraries要严格保证与你的版本对应，对应关系可以访问[https://github.com/pyg-team/pytorch_geometric](https://github.com/pyg-team/pytorch_geometric)

```python
import sys
import torch

print("Python version:", sys.version)
print("PyTorch version:", torch.__version__)
print("CUDA version:", torch.version.cuda)
```

**Comment by daetz-coder** [comment]
> 环境里面的安装包你是根据yet-another-vectornet里的安装包安装的吗？

不是根据yet-another-vectornet的requirements.txt进行安装的，大部分都是常见的依赖，直接pip就行，有几点需要注意的是：

- 安装argoverse-api时可能会出现numpy版本错误，修改setup.py中的版本即可

- 安装PyG及其Additional Libraries要严格保证与你的版本对应，对应关系可以访问[https://github.com/pyg-team/pytorch_geometric](https://github.com/pyg-team/pytorch_geometric)

```python
import sys
import torch

print("Python version:", sys.version)
print("PyTorch version:", torch.__version__)
print("CUDA version:", torch.version.cuda)
```

**Comment by xiaochong18** [comment]
小白，不懂什么原因
![Uploading 屏幕截图 2024-11-06 194222.png…]()

**Comment by xiaochong18** [comment]
![屏幕截图 2024-11-06 194222](https://github.com/user-attachments/assets/f404fd21-d549-4f1c-baf4-154f7fcefa4c)
这是什么问题，求求求
!python compute_feature_module.py

folder: .ipynb_checkpoints
Traceback (most recent call last):
  File "compute_feature_module.py", line 30, in <module>
    afl = ArgoverseForecastingLoader(os.path.join(DATA_DIR, folder))
  File "/root/autodl-tmp/vectornet/argoverse-api/argoverse/data_loading/argoverse_forecasting_loader.py", line 39, in __init__
    self.current_seq: Path = self.seq_list[self.counter]
IndexError: list index out of range

**Comment by daetz-coder** [comment]
> ![屏幕截图 2024-11-06 194222](https://private-user-images.githubusercontent.com/103839270/383539774-f404fd21-d549-4f1c-baf4-154f7fcefa4c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4OTUzOTUsIm5iZiI6MTczMDg5NTA5NSwicGF0aCI6Ii8xMDM4MzkyNzAvMzgzNTM5Nzc0LWY0MDRmZDIxLWQ1NDktNGYxYy1iYWY0LTE1NGY3ZmNlZmE0Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNlQxMjExMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZGNkZGI4NDQyODAxZDI0ZDljNTAyNGU2YjllNmRhMDA0M2VjYzUxNTg0ODgzYmM4NGNjNTYwNzQ0OWMwY2ViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.D9be8uz82saqrInM3i0DeIRKwijUDuSeW9zYNuwjZbY) 这是什么问题，求求求 !python compute_feature_module.py
> 
> folder: .ipynb_checkpoints Traceback (most recent call last): File "compute_feature_module.py", line 30, in afl = ArgoverseForecastingLoader(os.path.join(DATA_DIR, folder)) File "/root/autodl-tmp/vectornet/argoverse-api/argoverse/data_loading/argoverse_forecasting_loader.py", line 39, in **init** self.current_seq: Path = self.seq_list[self.counter] IndexError: list index out of range

你好，我刚刚检查了一下代码，由于原作者在*compute_feature_module.py*中使用*os.listdir()*获取文件夹，但os.listdir()同时还会获取文件及其隐藏文件，又由于*jupyter-lab*经常出现*.ipynb_checkpoints*检查点，导致你这个隐藏文件被os.listdir()捕获了，这也就是你第一行出现*folder: .ipynb_checkpoints *的原因。
+ 如何修复
你可以在data文件夹下使用`ll` 或者`ls` 再使用`rm .ipynb_checkpoints`删除即可。

**Comment by xiaochong18** [comment]
@daetz-coder 感谢，文章写得很详细，代码已经跑通了。有问题的的话还会回来请教大佬，再次感谢
